// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package index

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/ErikJermanis/erikjermanis.me/views/layouts"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col items-center p-3\"><h1 class=\"text-4xl text-center text-slate-700\"><span class=\"text-5xl font-semibold\">Erik Jermaniš</span><br><span>Software engineer</span></h1><p class=\"text-center text-lg font-bold italic mt-4\">I get things done.</p><p class=\"text-center mt-9\">I'm based in Rijeka, Croatia, but I like working remotely.</p><p class=\"mt-2\">Here is my <a href=\"https://cv.erikjermanis.me/\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"font-medium text-sky-700\">CV</a></p><p class=\"text-center mt-2\">For all inquiries send me an email: <a href=\"mailto:erik55jermanis@gmail.com\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"font-medium text-sky-700\">erik55jermanis@gmail.com</a></p><a href=\"https://github.com/ErikJermanis\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"font-medium text-sky-700 mt-8\">Github</a> <a href=\"https://x.com/ej_dev1\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"font-medium text-sky-700 mt-0.5\">X / Twitter</a> <a href=\"https://www.linkedin.com/in/erik-jermanis/\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"font-medium text-sky-700 mt-0.5\">Linkedin</a></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base("Erik Jermaniš - Software engineer").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
